# Generated by Django 3.2.7 on 2022-11-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, null=True)),
                ('inp6', models.CharField(default='', max_length=20, null=True)),
                ('inp7', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=40)),
                ('cipher', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_name', models.CharField(default='', max_length=20, null=True)),
                ('inp1', models.CharField(default='', max_length=20, null=True)),
                ('inp2', models.CharField(default='', max_length=20, null=True)),
                ('inp3', models.CharField(default='', max_length=20, null=True)),
                ('inp4', models.CharField(default='', max_length=20, null=True)),
                ('inp5', models.CharField(default='', max_length=20, null=True)),
                ('Code_it_calc', models.BooleanField(default=True, verbose_name='')),
                ('cipher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_orders.cipher')),
            ],
        ),
    ]
