# Generated by Django 3.2.7 on 2022-11-17 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_orders', '0003_auto_20221118_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product/')),
            ],
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('SUPPLIER', 'SUPPLIER'), ('CONSUMER', 'CONSUMER')], max_length=15),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.FloatField(blank=True)),
                ('images', models.ManyToManyField(to='online_orders.ImageAttachment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
