# Generated by Django 3.2.7 on 2022-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_orders', '0006_product_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Unique_no',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
