# Generated by Django 3.2.7 on 2022-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_orders', '0007_auto_20221120_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(blank=True),
        ),
    ]
