# Generated by Django 3.2.7 on 2022-11-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_orders', '0008_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Unique_no',
            new_name='unique_no',
        ),
    ]
