# Generated by Django 3.2.7 on 2022-11-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_orders', '0009_rename_unique_no_product_unique_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_orders.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageAttachment',
        ),
    ]
