# Generated by Django 3.2.7 on 2022-11-26 20:12

from django.db import migrations, models
import online_orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('online_orders', '0011_auto_20221127_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_no',
            field=models.CharField(blank=True, default=online_orders.models.Product.create_new_unique_no, max_length=8),
        ),
    ]
